namespace Tmui.Core;

public enum Key
{
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, R, S, Q, T, U, W, X, Y, Z,
    Alpha0, Alpha1, Alpha2, Alpha3, Alpha4, Alpha5, Alpha6, Alpha7, Alpha8, Alpha9,
    Tilde, Minus, Plus, Enter, Tab, CapsLock, LeftShift, LeftCtrl, LeftAlt,
    RightAlt, RightCtrl, Command, Windows = Command, LeftBracket, RightBracket,
    BackSlash, Comma, Dot, FwdSlash, PrtSc, ScrLk, Pause, Insert, Home,
    PageUp, PageDown, Delete, End, UpArrow, DownArrow, LeftArrow, RightArrow,
    NumLock, NumpadDivide, NumpadMultiply, NumpadMinus, NumpadPlus,
    Numpad0, Numpad1, Numpad2, Numpad3, Numpad4, Numpad5, Numpad6, Numpad7, Numpad8, Numpad9,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    MouseLeft, MouseMiddle, MouseRight, Mouse1, Mouse2,
    Backspace,
    Space,
    V,
    Super,
    SuperRight,
    RightSuper,
    NumpadDot,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    RightShift,
    Quote,
    Unknown
}
